### ISSUE TITLE
session-error with german-umlauts

### ISSUE THREAD

**Issue by agi-internet** [AlkimMedia/AmazonPay_Modified_2070#1]
Hi, if the shops name contains german umlauts, the amazon-session could not be created in ISO-8859-1- shops.
I think the shops data ist not encoded to utf-8 before the json-string ist created.

**Comment by mkreusch** [comment]
Hi @agi-internet 
Thanks for letting us know. We'll check on this and get back to you asap.

**Comment by AlkimMedia** [comment]
Hi @agi-internet!

We just published a fix for this issue in https://github.com/AlkimMedia/AmazonPay_Modified_2070/commit/752da4366a512aae16909e1036173ba34c5486e0
